/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Universe */
        get: operations["get_universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quote/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_quote__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quotes */
        get: operations["get_quotes_api_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_history__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financials/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Financials */
        get: operations["get_financials_api_financials__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ratios/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ratios */
        get: operations["get_ratios_api_ratios__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Peers */
        get: operations["get_peers_api_peers__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/valuation/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Valuation */
        get: operations["get_valuation_api_valuation__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_events__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_overview__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Glossary */
        get: operations["get_glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AltmanZComponentOut */
        AltmanZComponentOut: {
            /** Label */
            label: string;
            /** Value */
            value: number | null;
        };
        /** AltmanZDetailOut */
        AltmanZDetailOut: {
            /** Score */
            score: number | null;
            /** Zone */
            zone: ("safe" | "grey" | "distress") | null;
            /** Components */
            components: components["schemas"]["AltmanZComponentOut"][];
        };
        /** AxisComponent */
        AxisComponent: {
            /** Metric */
            metric: string;
            /** Value */
            value: number | null;
            /** Weight */
            weight: number;
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Percentile */
            percentile: number | null;
        };
        /** AxisResult */
        AxisResult: {
            /** Score */
            score: number | null;
            /** Components */
            components: components["schemas"]["AxisComponent"][];
        };
        /** BalanceSheetPeriodDetail */
        BalanceSheetPeriodDetail: {
            /** Fiscal Year */
            fiscal_year: string;
            /** Period End */
            period_end: string;
            /** Assets */
            assets: {
                [key: string]: number | null;
            };
            /** Liabilities Equity */
            liabilities_equity: {
                [key: string]: number | null;
            };
            /** Balance Check Pct */
            balance_check_pct: number | null;
            /** Net Debt */
            net_debt: number | null;
            /** Bvps */
            bvps: number | null;
        };
        /** CashFlowPeriodDetail */
        CashFlowPeriodDetail: {
            /** Fiscal Year */
            fiscal_year: string;
            /** Period End */
            period_end: string;
            /** Cfo To Ebitda */
            cfo_to_ebitda: number | null;
            /** Cfo To Pat */
            cfo_to_pat: number | null;
            /** Fcf Margin Pct */
            fcf_margin_pct: number | null;
        };
        /** CashFlowSankey */
        CashFlowSankey: {
            /** Links */
            links: components["schemas"]["CashFlowSankeyLink"][];
            /** Computed Change In Cash */
            computed_change_in_cash: number | null;
            /** Reported Change In Cash */
            reported_change_in_cash: number | null;
            /** Gap */
            gap: number | null;
        };
        /** CashFlowSankeyLink */
        CashFlowSankeyLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Value */
            value: number;
        };
        /** CompanyRef */
        CompanyRef: {
            /** Symbol */
            symbol: string;
            /** Yf Ticker */
            yf_ticker: string;
            /** Name */
            name: string;
            /**
             * Template
             * @enum {string}
             */
            template: "bank" | "nbfc" | "insurance" | "exchange" | "general";
        };
        /** DividendEvent */
        DividendEvent: {
            /** Date */
            date: string;
            /** Amount */
            amount: number;
        };
        /** EventsResponse */
        EventsResponse: {
            /** Symbol */
            symbol: string;
            /** Dividends */
            dividends: components["schemas"]["DividendEvent"][];
            /** Splits */
            splits: components["schemas"]["SplitEvent"][];
            /** News */
            news: Record<string, never>[];
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** FinancialPeriod */
        FinancialPeriod: {
            /** Fiscal Year */
            fiscal_year: string;
            /** Period End */
            period_end: string;
            /** Line Items */
            line_items: {
                [key: string]: number | null;
            };
        };
        /** FinancialsResponse */
        FinancialsResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Period
             * @enum {string}
             */
            period: "annual" | "quarterly";
            /** Income Statement */
            income_statement: components["schemas"]["FinancialPeriod"][];
            /** Balance Sheet */
            balance_sheet: components["schemas"]["FinancialPeriod"][];
            /** Cash Flow */
            cash_flow: components["schemas"]["FinancialPeriod"][];
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
            /** Notes */
            notes?: string[];
            /** Comparable From */
            comparable_from?: string | null;
            /** Comparable From Label */
            comparable_from_label?: string | null;
            /** Balance Sheet Detail */
            balance_sheet_detail?: components["schemas"]["BalanceSheetPeriodDetail"][];
            /** Cash Flow Detail */
            cash_flow_detail?: components["schemas"]["CashFlowPeriodDetail"][];
            cash_flow_sankey?: components["schemas"]["CashFlowSankey"] | null;
        };
        /** GlossaryEntry */
        GlossaryEntry: {
            /** Label */
            label: string;
            /** Formula */
            formula: string;
            /** Meaning */
            meaning: string;
            /** Good Looks Like */
            good_looks_like: string;
        };
        /** GlossaryResponse */
        GlossaryResponse: {
            /** Entries */
            entries: {
                [key: string]: components["schemas"]["GlossaryEntry"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Symbol */
            symbol: string;
            /** Range */
            range: string;
            /** Interval */
            interval: string;
            /** Bars */
            bars: components["schemas"]["OHLCVBar"][];
            /** Benchmark Bars */
            benchmark_bars?: components["schemas"]["OHLCVBar"][];
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** OHLCVBar */
        OHLCVBar: {
            /** Date */
            date: string;
            /** Open */
            open?: number | null;
            /** High */
            high?: number | null;
            /** Low */
            low?: number | null;
            /** Close */
            close?: number | null;
            /** Volume */
            volume?: number | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Symbol */
            symbol: string;
            /** Beta */
            beta?: number | null;
            /** Analyst Target Mean */
            analyst_target_mean?: number | null;
            /** Analyst Target High */
            analyst_target_high?: number | null;
            /** Analyst Target Low */
            analyst_target_low?: number | null;
            /** Analyst Count */
            analyst_count?: number | null;
            /** Analyst Recommendation */
            analyst_recommendation?: string | null;
            /** Relative Performance Vs Nifty50 Pp */
            relative_performance_vs_nifty50_pp?: number | null;
            /** Relative Performance Vs Sector Pp */
            relative_performance_vs_sector_pp?: number | null;
            /**
             * Sector Peer Count
             * @default 0
             */
            sector_peer_count: number;
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** PeerRow */
        PeerRow: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /**
             * Template
             * @enum {string}
             */
            template: "bank" | "nbfc" | "insurance" | "exchange" | "general";
            /** Last Price */
            last_price: number | null;
            /** Market Cap */
            market_cap: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
        };
        /** PeersResponse */
        PeersResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Peer Basis
             * @enum {string}
             */
            peer_basis: "sector" | "template" | "none";
            /** Peers */
            peers: components["schemas"]["PeerRow"][];
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** PiotroskiDetailOut */
        PiotroskiDetailOut: {
            /** Earned */
            earned: number;
            /** Possible */
            possible: number;
            /** Tests */
            tests: components["schemas"]["PiotroskiTestOut"][];
        };
        /** PiotroskiTestOut */
        PiotroskiTestOut: {
            /** Label */
            label: string;
            /** Passed */
            passed: boolean | null;
        };
        /** QualityScores */
        QualityScores: {
            altman: components["schemas"]["AltmanZDetailOut"];
            piotroski?: components["schemas"]["PiotroskiDetailOut"] | null;
        };
        /** QuoteResponse */
        QuoteResponse: {
            /** Symbol */
            symbol: string;
            /** Yf Ticker */
            yf_ticker: string;
            /** Last Price */
            last_price?: number | null;
            /** Change */
            change?: number | null;
            /** Change Pct */
            change_pct?: number | null;
            /** Open */
            open?: number | null;
            /** Day High */
            day_high?: number | null;
            /** Day Low */
            day_low?: number | null;
            /** Prev Close */
            prev_close?: number | null;
            /** Volume */
            volume?: number | null;
            /** Week52 High */
            week52_high?: number | null;
            /** Week52 Low */
            week52_low?: number | null;
            /** Market Cap */
            market_cap?: number | null;
            /**
             * Market Status
             * @default closed
             * @enum {string}
             */
            market_status: "open" | "closed" | "pre_open";
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** RatioHistoryPoint */
        RatioHistoryPoint: {
            /** Fiscal Year */
            fiscal_year: string;
            /** Period End */
            period_end: string;
            /** Value */
            value: number | null;
        };
        /** RatioValue */
        RatioValue: {
            /** Value */
            value: number | null;
            /** Peer Median */
            peer_median: number | null;
            /** Peer Min */
            peer_min?: number | null;
            /** Peer Max */
            peer_max?: number | null;
            /** Percentile */
            percentile: number | null;
            /**
             * Method
             * @default unavailable
             * @enum {string}
             */
            method: "computed" | "yahoo_fallback" | "unavailable";
            /**
             * Data Quality
             * @default ok
             * @enum {string}
             */
            data_quality: "ok" | "inconsistent";
            /** Data Quality Reason */
            data_quality_reason?: string | null;
            /** Reason */
            reason?: ("missing" | "not_meaningful") | null;
            /**
             * Direction
             * @default higher_better
             * @enum {string}
             */
            direction: "higher_better" | "lower_better" | "neutral";
        };
        /** RatiosResponse */
        RatiosResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Template
             * @enum {string}
             */
            template: "bank" | "nbfc" | "insurance" | "exchange" | "general";
            /**
             * Peer Basis
             * @enum {string}
             */
            peer_basis: "sector" | "template" | "none";
            /** Peer Count */
            peer_count: number;
            /** Comparable Annual Years */
            comparable_annual_years: number;
            /** Growth Note */
            growth_note?: string | null;
            /** Ratios */
            ratios: {
                [key: string]: components["schemas"]["RatioValue"];
            };
            /** Health Radar */
            health_radar: {
                [key: string]: components["schemas"]["AxisResult"];
            };
            /** History */
            history?: {
                [key: string]: components["schemas"]["RatioHistoryPoint"][];
            };
            /** Dupont Kind */
            dupont_kind?: ("general" | "bank") | null;
            /** Dupont Reconciliation Gap Pp */
            dupont_reconciliation_gap_pp?: number | null;
            /** Signals */
            signals?: components["schemas"]["Signal"][];
            quality_scores?: components["schemas"]["QualityScores"] | null;
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** SectorGroup */
        SectorGroup: {
            /** Name */
            name: string;
            /** Companies */
            companies: components["schemas"]["CompanyRef"][];
        };
        /** Signal */
        Signal: {
            /**
             * Type
             * @enum {string}
             */
            type: "strength" | "watch";
            /** Rule */
            rule: string;
            /** Message */
            message: string;
            /** Values */
            values: {
                [key: string]: number | null;
            };
        };
        /** SplitEvent */
        SplitEvent: {
            /** Date */
            date: string;
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
        };
        /** UniverseResponse */
        UniverseResponse: {
            /** Sectors */
            sectors: components["schemas"]["SectorGroup"][];
            /**
             * Source
             * @default backend/data/nifty50.json
             */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValuationResponse */
        ValuationResponse: {
            /** Symbol */
            symbol: string;
            /** Multiples */
            multiples: {
                [key: string]: number | null;
            };
            /** Dcf */
            dcf: {
                [key: string]: number | null;
            };
            /** Dcf Inputs */
            dcf_inputs: {
                [key: string]: number | null;
            };
            /** Reverse Dcf Implied Growth Pct */
            reverse_dcf_implied_growth_pct: number | null;
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Warnings */
            warnings?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
        };
    };
    get_quote_api_quote__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quotes_api_quotes_get: {
        parameters: {
            query: {
                /** @description Comma-separated symbols */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_history__symbol__get: {
        parameters: {
            query?: {
                range?: string;
                interval?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_financials_api_financials__symbol__get: {
        parameters: {
            query?: {
                period?: "annual" | "quarterly";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ratios_api_ratios__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatiosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_peers_api_peers__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_valuation_api_valuation__symbol__get: {
        parameters: {
            query?: {
                /** @description Override the DCF's forecast growth rate (%) */
                growth_rate_pct?: number | null;
                /** @description Discount rate (%) */
                wacc_pct?: number;
                /** @description Terminal growth rate (%) */
                terminal_growth_pct?: number;
                forecast_years?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_events__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_overview__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
